import { beforeEach, afterEach, it, expect, vi } from 'vitest'
beforeEach(() => vi.resetModules())
afterEach(() => vi.unstubAllGlobals())
it('keeps credentials out of API URLs/storage and adds CSRF only to same-origin requests', async () => {
  const native = vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => ({ enabled: true, authenticated: true, csrf: 'nonce' }) })
  vi.stubGlobal('fetch', native)
  const auth = await import('./consoleAuth')
  auth.installConsoleAuth()
  expect(await auth.signIn('operator-secret')).toBe(true)
  await window.fetch('/api/probe', { method: 'POST' })
  expect(new Headers(native.mock.calls[2]![1].headers).get('X-Herald-CSRF')).toBe('nonce')
  expect(new Headers(native.mock.calls[2]![1].headers).get('Authorization')).toBeNull()
  await window.fetch('https://example.com/api/probe', { method: 'POST' })
  expect(native.mock.calls[3]![1]).toEqual({ method: 'POST' })
  expect(native.mock.calls[0]![0]).toBe('/auth/session')
  expect(localStorage.getItem('herald-token')).toBeNull()
})
it('rejects missing session cookie and marks expired API access locked', async () => {
  const native = vi.fn().mockResolvedValue({ ok: true, status: 200, json: async () => ({ enabled: true, authenticated: false, csrf: '' }) })
  vi.stubGlobal('fetch', native)
  const auth = await import('./consoleAuth')
  auth.installConsoleAuth()
  expect(await auth.signIn('operator-secret')).toBe(false)
  expect(auth.authError.value).toContain('cookie')
  auth.authenticated.value = true
  native.mockResolvedValueOnce({ ok: false, status: 401 })
  await window.fetch('/api/probe')
  expect(auth.authenticated.value).toBe(false)
})
